[character]
success_symbol = "âœ… "
error_symbol = "âŒ "

[git_branch]
symbol = "ğŸŒ¿ "
style = "bold green"

[git_status]
style = "bold yellow"
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bold blue"

[time]
format = "ğŸ•’ {$T}"
#time_format = "%H:%M:%S"
style = "italic grey"
disabled = true

[cmd_duration]
min_time = 1000
format = "â±ï¸ $duration"
style = "bold magenta"
